### ISSUE TITLE
Todo for merge

### ISSUE THREAD

**Issue by codykarcher** [codykarcher/pyomo#14]
- [ ] update documention on runtime constratint construction to be more consistent
- [x] merge constraint and runtime into one constructor
- [x] standard output hook
- [x] namespace hook (val, jac, hess)
- [x] runcase function (not in black box)

**Comment by codykarcher** [comment]
Choosing not to merge `Constraint` and `RuntimeConstraint` constructors.  Doing so would require more complex and less explicit code, and would also hide the distinction from the user, which I do not want.  @blnicho
